### ISSUE TITLE
SelectWidget is broken

### ISSUE THREAD

**Issue by jbpenrath** [openfun/verna#60]
### Problematic behavior
In the playground example, user cannot add a new `SelectWidget`.

### Expected behavior/code
In the playground example, user should be able to add a new `SelectWidget`.

### Steps to Reproduce
1. Start the playground example
2. Drop a `SelectWidget` into the form
3. Click on "Field parameters"
4. Add options
5. Click on save
6. ... and boom 💥

#### Environment
url : https://openfun.github.io/verna/

### Additional context/Screenshots
```
index.d74c32a0.js:32 TypeError: Cannot read properties of undefined (reading '0')
    at index.d74c32a0.js:116:54238
    at Array.map (<anonymous>)
    at eae (index.d74c32a0.js:116:54210)
    at _a (index.d74c32a0.js:116:54714)
    at enum (index.d74c32a0.js:116:55423)
    at v (index.d74c32a0.js:116:56132)
    at index.d74c32a0.js:116:56159
    at Array.forEach (<anonymous>)
    at aae (index.d74c32a0.js:116:56148)
    at Object.p [as onSubmit] (index.d74c32a0.js:116:62118)
```

![2022-11-09 12 28 45](https://user-images.githubusercontent.com/9265241/200819010-21c6ec2c-4698-4315-9871-5e537d79578b.gif)

**Comment by jbpenrath** [comment]
Fixed by #59
